const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: 'https://source.unsplash.com/yxZSAjyToP4',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'Mega Burger',
    category: 'lunch',
    price: 19.99,
    img: 'https://source.unsplash.com/Op6iy0YoYzg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'awesome milkshake',
    category: 'shakes',
    price: 6.99,
    img: 'https://source.unsplash.com/ewOrvEa87j4',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'country benedict',
    category: 'breakfast',
    price: 14.99,
    img: 'https://source.unsplash.com/xEf1wkWWDJM',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg toast',
    category: 'lunch',
    price: 12.99,
    img: 'https://source.unsplash.com/ya5oLwJff4g',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'chocolate dream',
    category: 'shakes',
    price: 6.99,
    img: 'https://source.unsplash.com/DEovggNHhe0',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'french toast',
    category: 'breakfast',
    price: 12.99,
    img: 'https://source.unsplash.com/0XGWys_GaFo',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 14.99,
    img: 'https://source.unsplash.com/5tC2YOVXE9Y',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: 'https://source.unsplash.com/Of1zmMWMZ9A',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: 'dinner buffet',
    category: 'dinner',
    price: 24.99,
    img: 'https://source.unsplash.com/a-8LxEvb4kU',
    desc: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui veniam quod sequi fugit. Iusto distinctio cum in cupiditate explicabo eius!`,
  },
];
export default menu;
